### ISSUE TITLE
Would love to see pictures and specs / schematics of your light poles

### ISSUE THREAD

**Issue by woodsnick** [trgregg/BikeSaber#1]
Saw your poles on bikes in SF in Golden Gate Park maybe a year ago or so. Loved them and starting to think about a light pole project of my own that I wanted to work on. Would love to see your pole design again, maybe a few pics, plus the hardware / battery specs you ended up putting together.

Can always shoot directly to me at nwoods@gmail.com. Much 🙏 and hope to run into you on the playa this year 🔥

**Comment by trgregg** [comment]
Better late than never. Finally created a real readme that includes pics and instructions.
